name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pdfminer.six scikit-learn matplotlib pydantic-settings
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest -q --cov=ktflow --cov-report=term-missing

